'use client';

import { useState } from 'react';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';

interface GeneratedDMCANotice {
  subject: string;
  body: string;
  recipient_email: string;
  recipient_name: string;
  recipient_form_url?: string | null;
  legal_references: string[];
  evidence_links: string[];
  sworn_statement: string;
  profile?: string;
}

interface QualityResult {
  passed: boolean;
  score: number;
  strength: 'strong' | 'standard' | 'weak';
  errors: Array<{ code: string; message: string; fix: string }>;
  warnings: Array<{ code: string; message: string; fix: string }>;
}

interface DMCALetterReviewProps {
  notice: GeneratedDMCANotice;
  quality?: QualityResult;
  productName: string;
  infringementUrl: string;
  onClose: () => void;
  onCopy: () => void;
}

export function DMCALetterReview({
  notice,
  quality,
  productName,
  infringementUrl,
  onClose,
  onCopy,
}: DMCALetterReviewProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedSubject, setEditedSubject] = useState(notice.subject);
  const [editedBody, setEditedBody] = useState(notice.body);
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const fullLetter = `Subject: ${editedSubject}\n\nTo: ${notice.recipient_name} <${notice.recipient_email}>\n\n${editedBody}`;

    navigator.clipboard.writeText(fullLetter);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    onCopy();
  };

  const handleDownload = () => {
    const fullLetter = `Subject: ${editedSubject}\n\nTo: ${notice.recipient_name}\nEmail: ${notice.recipient_email}\n\n${editedBody}\n\n---\nGenerated by ProductGuard.ai`;

    const blob = new Blob([fullLetter], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `DMCA-Notice-${productName.replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Determine strength based on score thresholds: <75 red, 75-84 yellow, 85+ green
  const getStrengthFromScore = (score: number) => {
    if (score >= 85) return 'strong';
    if (score >= 75) return 'standard';
    return 'weak';
  };

  const strengthConfig = {
    strong: { bg: 'bg-green-100 dark:bg-green-500/20', border: 'border-green-400 dark:border-green-500/50', barColor: 'bg-green-500', label: 'Strong' },
    standard: { bg: 'bg-yellow-100 dark:bg-yellow-500/20', border: 'border-yellow-400 dark:border-yellow-500/50', barColor: 'bg-yellow-500', label: 'Standard' },
    weak: { bg: 'bg-red-100 dark:bg-red-500/20', border: 'border-red-400 dark:border-red-500/50', barColor: 'bg-red-500', label: 'Weak' },
  };

  const effectiveStrength = quality ? getStrengthFromScore(quality.score) : null;
  const strengthStyle = effectiveStrength ? strengthConfig[effectiveStrength] : null;

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-end sm:items-center justify-center sm:p-4">
      <Card className="max-w-4xl w-full max-h-[85vh] sm:max-h-[90vh] overflow-y-auto rounded-b-none sm:rounded-b-2xl">
        {/* Header */}
        <div className="flex items-start justify-between mb-3 sm:mb-4 pb-3 sm:pb-4 border-b border-pg-border">
          <div>
            <h2 className="text-lg sm:text-2xl font-bold text-pg-text mb-1">DMCA Takedown Notice</h2>
            <p className="text-xs sm:text-sm text-pg-text-muted">Review and edit before sending</p>
          </div>
          <button
            onClick={onClose}
            className="text-pg-text-muted hover:text-pg-text transition-colors"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Quality Score Bar */}
        {quality && strengthStyle && (
          <div className={`mb-4 p-4 rounded-lg ${strengthStyle.bg} border ${strengthStyle.border}`}>
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <span className="text-sm font-bold text-gray-900 dark:text-gray-900">
                  Notice Strength: {strengthStyle.label}
                </span>
                <span className={`px-2 py-0.5 rounded text-xs font-bold text-gray-900 ${strengthStyle.barColor}/30`}>
                  {quality.score}/100
                </span>
              </div>
              {!quality.passed && (
                <span className="text-xs text-gray-900 dark:text-gray-900 font-semibold">
                  Missing required elements
                </span>
              )}
            </div>

            {/* Score Bar */}
            <div className="w-full h-2 bg-black/20 rounded-full overflow-hidden mb-3">
              <div
                className={`h-full rounded-full transition-all duration-500 ${strengthStyle.barColor}`}
                style={{ width: `${quality.score}%` }}
              />
            </div>

            {/* Errors */}
            {quality.errors.length > 0 && (
              <div className="mb-2">
                {quality.errors.map((err, i) => (
                  <div key={i} className="flex items-start gap-2 text-xs mb-1">
                    <span className="text-gray-900 dark:text-gray-900 mt-0.5 shrink-0 font-bold">✕</span>
                    <span className="text-gray-900 dark:text-gray-900">
                      <strong>{err.message}</strong> — {err.fix}
                    </span>
                  </div>
                ))}
              </div>
            )}

            {/* Warnings */}
            {quality.warnings.length > 0 && (
              <div>
                {quality.warnings.map((warn, i) => (
                  <div key={i} className="flex items-start gap-2 text-xs mb-1">
                    <span className="text-gray-900 dark:text-gray-900 mt-0.5 shrink-0 font-bold">!</span>
                    <span className="text-gray-800 dark:text-gray-900">
                      {warn.message} — <span className="italic">{warn.fix}</span>
                    </span>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* Product & Infringement Info */}
        <div className="mb-6 p-4 bg-pg-surface rounded-lg">
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <span className="text-pg-text-muted">Product:</span>
              <p className="font-semibold text-pg-text">{productName}</p>
            </div>
            <div>
              <span className="text-pg-text-muted">Infringing URL:</span>
              <p className="font-medium text-pg-accent truncate">{infringementUrl}</p>
            </div>
          </div>
        </div>

        {/* Recipient Info */}
        <div className="mb-6">
          <h3 className="text-sm font-bold text-pg-text mb-2">Send To</h3>
          <div className="p-3 bg-pg-bg rounded-lg text-sm space-y-1">
            <p className="font-semibold text-pg-text">{notice.recipient_name}</p>
            {notice.recipient_email && (
              <p className="text-pg-accent">{notice.recipient_email}</p>
            )}
            {notice.recipient_form_url && (
              <div className="flex items-center gap-2 mt-2 pt-2 border-t border-pg-border">
                <span className="text-xs text-pg-text-muted">This provider prefers web form submissions:</span>
                <a
                  href={notice.recipient_form_url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs text-pg-accent hover:underline font-medium"
                >
                  Open DMCA Form →
                </a>
              </div>
            )}
          </div>
        </div>

        {/* Subject Line */}
        <div className="mb-6">
          <div className="flex items-center justify-between mb-2">
            <h3 className="text-sm font-bold text-pg-text">Subject Line</h3>
            {!isEditing && (
              <Button size="sm" variant="ghost" onClick={() => setIsEditing(true)}>
                Edit
              </Button>
            )}
          </div>
          {isEditing ? (
            <input
              type="text"
              value={editedSubject}
              onChange={(e) => setEditedSubject(e.target.value)}
              className="w-full px-4 py-2 bg-pg-bg border border-pg-border rounded-lg text-pg-text focus:outline-none focus:ring-2 focus:ring-pg-accent"
            />
          ) : (
            <div className="p-3 bg-pg-bg rounded-lg">
              <p className="text-pg-text font-medium">{editedSubject}</p>
            </div>
          )}
        </div>

        {/* Letter Body */}
        <div className="mb-6">
          <div className="flex items-center justify-between mb-2">
            <h3 className="text-sm font-bold text-pg-text">Letter Body</h3>
            {!isEditing && (
              <Button size="sm" variant="ghost" onClick={() => setIsEditing(true)}>
                Edit
              </Button>
            )}
          </div>
          {isEditing ? (
            <textarea
              value={editedBody}
              onChange={(e) => setEditedBody(e.target.value)}
              rows={20}
              className="w-full px-4 py-3 bg-pg-bg border border-pg-border rounded-lg text-pg-text font-mono text-sm focus:outline-none focus:ring-2 focus:ring-pg-accent resize-none"
            />
          ) : (
            <div className="p-4 bg-pg-bg rounded-lg border border-pg-border max-h-96 overflow-y-auto">
              <pre className="whitespace-pre-wrap font-sans text-sm text-pg-text leading-relaxed">
                {editedBody}
              </pre>
            </div>
          )}
        </div>

        {/* Legal References */}
        <div className="mb-6 p-4 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg">
          <h3 className="text-sm font-bold text-yellow-900 dark:text-yellow-400 mb-2">
            Legal References
          </h3>
          <ul className="text-xs text-yellow-800 dark:text-yellow-500 space-y-1">
            {notice.legal_references.map((ref, i) => (
              <li key={i} className="flex items-center gap-2">
                <svg className="w-3 h-3 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                {ref}
              </li>
            ))}
            <li className="flex items-center gap-2">
              <svg className="w-3 h-3 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
              Good faith belief statement included
            </li>
            <li className="flex items-center gap-2">
              <svg className="w-3 h-3 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
              Accuracy statement under penalty of perjury included
            </li>
            <li className="flex items-center gap-2">
              <svg className="w-3 h-3 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
              Electronic signature included
            </li>
          </ul>
        </div>

        {/* Warning */}
        <div className="mb-6 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
          <h3 className="text-sm font-bold text-red-900 dark:text-red-400 mb-2">
            Important Legal Notice
          </h3>
          <p className="text-xs text-red-800 dark:text-red-500">
            By submitting this DMCA notice, you are making statements under penalty of perjury. False or misleading
            statements may subject you to civil liability. Review this notice carefully and consult with legal counsel
            if needed.
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center justify-between gap-4 pt-4 border-t border-pg-border">
          <div className="flex items-center gap-2">
            {isEditing && (
              <Button size="sm" variant="secondary" onClick={() => setIsEditing(false)}>
                Done Editing
              </Button>
            )}
          </div>
          <div className="flex items-center gap-2">
            <Button variant="secondary" onClick={handleDownload}>
              Download .txt
            </Button>
            <Button onClick={handleCopy}>
              {copied ? 'Copied!' : 'Copy to Clipboard'}
            </Button>
          </div>
        </div>

        {/* Next Steps */}
        <div className="mt-4 pt-4 border-t border-pg-border">
          <h3 className="text-sm font-bold text-pg-text mb-2">Next Steps</h3>
          <ol className="text-xs text-pg-text-muted space-y-1 list-decimal list-inside">
            {notice.recipient_form_url ? (
              <>
                <li>Open the provider&apos;s DMCA form (link above) and paste the notice</li>
                <li>Or copy to clipboard and send via email to: <span className="text-pg-accent font-mono">{notice.recipient_email || 'see form'}</span></li>
              </>
            ) : (
              <>
                <li>Copy the notice to your clipboard or download it</li>
                <li>Send via email to: <span className="text-pg-accent font-mono">{notice.recipient_email || 'provider contact'}</span></li>
              </>
            )}
            <li>Keep a copy for your records</li>
            <li>Mark infringement as &quot;Takedown Sent&quot; after sending</li>
          </ol>
        </div>
      </Card>
    </div>
  );
}
