'use client';

import { useState } from 'react';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';

interface GeneratedDMCANotice {
  subject: string;
  body: string;
  recipient_email: string;
  recipient_name: string;
  legal_references: string[];
  evidence_links: string[];
  sworn_statement: string;
}

interface DMCALetterReviewProps {
  notice: GeneratedDMCANotice;
  productName: string;
  infringementUrl: string;
  onClose: () => void;
  onCopy: () => void;
}

export function DMCALetterReview({
  notice,
  productName,
  infringementUrl,
  onClose,
  onCopy,
}: DMCALetterReviewProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedSubject, setEditedSubject] = useState(notice.subject);
  const [editedBody, setEditedBody] = useState(notice.body);
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const fullLetter = `Subject: ${editedSubject}\n\nTo: ${notice.recipient_name} <${notice.recipient_email}>\n\n${editedBody}`;

    navigator.clipboard.writeText(fullLetter);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    onCopy();
  };

  const handleDownload = () => {
    const fullLetter = `Subject: ${editedSubject}\n\nTo: ${notice.recipient_name}\nEmail: ${notice.recipient_email}\n\n${editedBody}\n\n---\nGenerated by ProductGuard.ai`;

    const blob = new Blob([fullLetter], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `DMCA-Notice-${productName.replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <Card className="max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-start justify-between mb-4 pb-4 border-b border-pg-border">
          <div>
            <h2 className="text-2xl font-bold text-pg-text mb-1">DMCA Takedown Notice</h2>
            <p className="text-sm text-pg-text-muted">Review and edit before sending</p>
          </div>
          <button
            onClick={onClose}
            className="text-pg-text-muted hover:text-pg-text transition-colors"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* AI Badge */}
        <div className="mb-4 flex items-center gap-2">
          <Badge variant="default" className="bg-blue-600">
            🤖 AI-Generated
          </Badge>
          <span className="text-xs text-pg-text-muted">
            Review for accuracy. You are legally responsible for the contents.
          </span>
        </div>

        {/* Product & Infringement Info */}
        <div className="mb-6 p-4 bg-pg-surface rounded-lg">
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <span className="text-pg-text-muted">Product:</span>
              <p className="font-semibold text-pg-text">{productName}</p>
            </div>
            <div>
              <span className="text-pg-text-muted">Infringing URL:</span>
              <p className="font-medium text-pg-accent truncate">{infringementUrl}</p>
            </div>
          </div>
        </div>

        {/* Recipient Info */}
        <div className="mb-6">
          <h3 className="text-sm font-bold text-pg-text mb-2">Recipient</h3>
          <div className="p-3 bg-pg-bg rounded-lg text-sm">
            <p className="font-semibold text-pg-text">{notice.recipient_name}</p>
            <p className="text-pg-accent">{notice.recipient_email}</p>
          </div>
        </div>

        {/* Subject Line */}
        <div className="mb-6">
          <div className="flex items-center justify-between mb-2">
            <h3 className="text-sm font-bold text-pg-text">Subject Line</h3>
            {!isEditing && (
              <Button size="sm" variant="ghost" onClick={() => setIsEditing(true)}>
                Edit
              </Button>
            )}
          </div>
          {isEditing ? (
            <input
              type="text"
              value={editedSubject}
              onChange={(e) => setEditedSubject(e.target.value)}
              className="w-full px-4 py-2 bg-pg-bg border border-pg-border rounded-lg text-pg-text focus:outline-none focus:ring-2 focus:ring-pg-accent"
            />
          ) : (
            <div className="p-3 bg-pg-bg rounded-lg">
              <p className="text-pg-text font-medium">{editedSubject}</p>
            </div>
          )}
        </div>

        {/* Letter Body */}
        <div className="mb-6">
          <div className="flex items-center justify-between mb-2">
            <h3 className="text-sm font-bold text-pg-text">Letter Body</h3>
            {!isEditing && (
              <Button size="sm" variant="ghost" onClick={() => setIsEditing(true)}>
                Edit
              </Button>
            )}
          </div>
          {isEditing ? (
            <textarea
              value={editedBody}
              onChange={(e) => setEditedBody(e.target.value)}
              rows={20}
              className="w-full px-4 py-3 bg-pg-bg border border-pg-border rounded-lg text-pg-text font-mono text-sm focus:outline-none focus:ring-2 focus:ring-pg-accent resize-none"
            />
          ) : (
            <div className="p-4 bg-pg-bg rounded-lg border border-pg-border max-h-96 overflow-y-auto">
              <pre className="whitespace-pre-wrap font-sans text-sm text-pg-text leading-relaxed">
                {editedBody}
              </pre>
            </div>
          )}
        </div>

        {/* Legal References */}
        <div className="mb-6 p-4 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg">
          <h3 className="text-sm font-bold text-yellow-900 dark:text-yellow-400 mb-2">
            ⚖️ Legal Requirements Met
          </h3>
          <ul className="text-xs text-yellow-800 dark:text-yellow-500 space-y-1">
            {notice.legal_references.map((ref, i) => (
              <li key={i}>• {ref}</li>
            ))}
            <li>• Good faith belief statement</li>
            <li>• Accuracy statement under penalty of perjury</li>
            <li>• Contact information provided</li>
          </ul>
        </div>

        {/* Warning */}
        <div className="mb-6 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
          <h3 className="text-sm font-bold text-red-900 dark:text-red-400 mb-2">
            ⚠️ Important Legal Notice
          </h3>
          <p className="text-xs text-red-800 dark:text-red-500">
            By submitting this DMCA notice, you are making statements under penalty of perjury. False or misleading
            statements may subject you to civil liability. Review this notice carefully and consult with legal counsel
            if needed.
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center justify-between gap-4 pt-4 border-t border-pg-border">
          <div className="flex items-center gap-2">
            {isEditing && (
              <Button size="sm" variant="secondary" onClick={() => setIsEditing(false)}>
                Done Editing
              </Button>
            )}
          </div>
          <div className="flex items-center gap-2">
            <Button variant="secondary" onClick={handleDownload}>
              📥 Download
            </Button>
            <Button onClick={handleCopy}>
              {copied ? '✓ Copied!' : '📋 Copy to Clipboard'}
            </Button>
          </div>
        </div>

        {/* Next Steps */}
        <div className="mt-4 pt-4 border-t border-pg-border">
          <h3 className="text-sm font-bold text-pg-text mb-2">Next Steps:</h3>
          <ol className="text-xs text-pg-text-muted space-y-1 list-decimal list-inside">
            <li>Copy the notice to your clipboard or download it</li>
            <li>Send via email to: <span className="text-pg-accent font-mono">{notice.recipient_email}</span></li>
            <li>Keep a copy for your records</li>
            <li>Update infringement status to "Takedown Sent" after sending</li>
          </ol>
        </div>
      </Card>
    </div>
  );
}
